add back junit report and codecov upload

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,22 +45,23 @@ jobs:
     - name: Common Test tests
       run: rebar3 ct --cover
 
-    # - name: Publish Test Report
-    #   uses: mikepenz/action-junit-report@v3
-    #   if: success() || failure() # always run even if the previous step fails
-    #   with:
-    #     report_paths: '**/_build/test/logs/*/junit_report.xml'
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/_build/test/logs/*/junit_report.xml'
 
     - name: XRef
       run: rebar3 xref
-    # - name: Covertool
-    #   if: ${{ always() }}
-    #   run: rebar3 covertool generate
-    # - uses: codecov/codecov-action@v3
-    #   if: ${{ always() }}
-    #   with:
-    #     file: _build/test/covertool/service_discovery.covertool.xml
-    #     env_vars: OTP_VERSION
+
+    - name: Covertool
+      if: ${{ always() }}
+      run: rebar3 covertool generate
+    - uses: codecov/codecov-action@v3
+      if: ${{ always() }}
+      with:
+        file: _build/test/covertool/service_discovery.covertool.xml
+        env_vars: OTP_VERSION
   dialyzer:
     name: Dialyze on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
