fixup github ci, removing junit report and codecov for now

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,7 +26,7 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     - name: Run Collector
-      run: docker-compose up -d
+      run: docker compose up -d
     - uses: erlef/setup-beam@v1
       with:
         otp-version: ${{ matrix.otp_version }}
@@ -45,22 +45,22 @@ jobs:
     - name: Common Test tests
       run: rebar3 ct --cover
 
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/_build/test/logs/*/junit_report.xml'
+    # - name: Publish Test Report
+    #   uses: mikepenz/action-junit-report@v3
+    #   if: success() || failure() # always run even if the previous step fails
+    #   with:
+    #     report_paths: '**/_build/test/logs/*/junit_report.xml'
 
     - name: XRef
       run: rebar3 xref
-    - name: Covertool
-      if: ${{ always() }}
-      run: rebar3 covertool generate
-    - uses: codecov/codecov-action@v3
-      if: ${{ always() }}
-      with:
-        file: _build/test/covertool/.covertool.xml
-        env_vars: OTP_VERSION
+    # - name: Covertool
+    #   if: ${{ always() }}
+    #   run: rebar3 covertool generate
+    # - uses: codecov/codecov-action@v3
+    #   if: ${{ always() }}
+    #   with:
+    #     file: _build/test/covertool/service_discovery.covertool.xml
+    #     env_vars: OTP_VERSION
   dialyzer:
     name: Dialyze on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
@@ -87,4 +87,4 @@ jobs:
     - name: Compile
       run: rebar3 compile
     - name: Dialyzer
-      run: rebar3 as dialyzer dialyzer
+      run: rebar3 dialyzer
